### ISSUE TITLE
Events Schema Missing Name

### ISSUE THREAD

**Issue by thaipablo** [singer-io/tap-outreach#9]
The schema for the Events resource does not include name, which is a fairly critical attribute of that resource.

**Comment by sgandhi1311** [comment]
@thaipablo If understood you correctly, I see the `name` key present in the events schema. Please let me know if you are looking for something else.

**Comment by sgandhi1311** [comment]
The field is already added in this PR - https://github.com/singer-io/tap-outreach/pull/13
